---
title: "Monthly core measures"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{metadata-monthly}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

> **Note:** This package currently only provides metadata for the most recent monthly reporting period.

```{r setup, include = FALSE}
library(nhstt)
library(dplyr)
library(gt)

# Metadata for monthly core measures
metadata_monthly <- get_metadata_monthly() |> 
  filter(measure_type == "Core") |> 
  select(measure_id, description)
```

```{r tab-measures-monthly, echo=FALSE}

metadata_monthly |> 
  gt() |> 
  tab_style(
    style = list(
      cell_text(align = "left", v_align = "top")
    ),
    locations = cells_body(columns = measure_id)
  ) |> 
  tab_style(
    style = list(
      cell_text(align = "left", v_align = "top")
    ),
    locations = cells_body(columns = description)
  ) |> 
  cols_label(
    measure_id = "ID",
    description = "Description"
  )
```