---
title: "Core measures"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Core measures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

> **Note:** This package currently only provides metadata for the most recent monthly reporting period. Older monthly periods might have less, or different measures.

```{r setup, include = FALSE}
library(nhstt)
library(dplyr)
library(reactable)

# Metadata for monthly core measures
metadata_monthly_core <- get_metadata_monthly() |>
  filter(measure_type == "Core") |>
  select(measure_id, description)
```

In total there are **`r length(unique(metadata_monthly_core$measure_id))`** monthly _core_ measures:

```{r tab-measures-monthly-core, echo=FALSE}

reactable(
  metadata_monthly_core,
  searchable = TRUE,
  sortable = FALSE,
  searchMethod = JS(
    "function(rows, columnIds, filterValue) {
    return rows.filter(function(row) {
      var measure = String(row.values['measure_id']).toLowerCase();
      var desc = String(row.values['description']).toLowerCase();
      var search = filterValue.toLowerCase();
      return measure.indexOf(search) >= 0 || desc.indexOf(search) >= 0;
    });
  }"
  ),
  defaultPageSize = nrow(metadata_monthly_core),
  columns = list(
    measure_id = colDef(
      name = "Measure ID and description",
      cell = function(value, index) {
        description <- metadata_monthly_core$description[index]
        htmltools::tags$div(
          htmltools::tags$code(
            style = "color: #2A788EFF;",
            value
          ),
          ": ",
          description
        )
      }
    ),
    description = colDef(show = FALSE)
  ),
  outlined = TRUE,
  striped = TRUE
)
```
