#' Get provider organisation metadata from ODS
#'
#' @param use_cache Logical, whether to use cached data if available. Default TRUE.
#'
#' @return Tibble with provider organisation metadata
#' @importFrom dplyr mutate select
#' @importFrom arrow read_parquet write_parquet
#'
#' @export
#' @examples
#' \dontrun{
#' # Get provider metadata
#' nhstt_providers <- get_metadata_providers()
#' }
get_metadata_providers <- function(use_cache = TRUE) {
  cache_path <- file.path(get_cache_dir(), "metadata_providers.parquet")

  if (use_cache && file.exists(cache_path)) {
    return(arrow::read_parquet(cache_path))
  }

  # All unique provider codes from annual data
  provider_codes <- c(
    "8J766",
    "AA5",
    "AD7",
    "AEY01",
    "AEY04",
    "AJA",
    "AKR01",
    "ALR01",
    "ALR02",
    "AM001",
    "AM5",
    "AM601",
    "AM7",
    "AM801",
    "AMC01",
    "AMC02",
    "AMC03",
    "AMC04",
    "AMD01",
    "AME01",
    "AML01",
    "AN2",
    "AN5",
    "AN901",
    "ANA01",
    "ANC",
    "ANV01",
    "ARY01",
    "AYV",
    "DA1",
    "DA201",
    "DA3",
    "DA4",
    "DA6",
    "DDF",
    "DH0",
    "DH8",
    "DHA",
    "NCH",
    "NCM",
    "NDC03",
    "NDC05",
    "NDC06",
    "NDC07",
    "NDC08",
    "NDC09",
    "NDC10",
    "NDC11",
    "NDC13",
    "NDC14",
    "NDC15",
    "NDC16",
    "NFG",
    "NFL",
    "NI382",
    "NI384",
    "NI385",
    "NI386",
    "NI397",
    "NI398",
    "NI399",
    "NIW",
    "NJG",
    "NJJ",
    "NKI",
    "NKT",
    "NLS",
    "NMQ",
    "NNE",
    "NNF",
    "NO202",
    "NO204",
    "NQL",
    "NQV",
    "NR5",
    "NWX08",
    "R1A",
    "R1C",
    "R1F",
    "R1L",
    "RAT",
    "RDR",
    "RDYDL",
    "RDYEV",
    "RDYLK",
    "RDYLL",
    "RE9",
    "RH5",
    "RHA",
    "RKE",
    "RKL07",
    "RKL14",
    "RKL42",
    "RLYD7",
    "RMY",
    "RNK02",
    "RNN",
    "RNUDT",
    "RNUDV",
    "RP1",
    "RP7",
    "RPG",
    "RQX",
    "RQY12",
    "RQYPR",
    "RRE",
    "RRP",
    "RT1",
    "RT2HQ",
    "RT2K2",
    "RTD",
    "RTF61",
    "RTQ",
    "RTV",
    "RV383",
    "RV3AR",
    "RV3CH",
    "RV3DG",
    "RV3HC",
    "RV3L8",
    "RV5CG",
    "RV5CH",
    "RV5CJ",
    "RV5CK",
    "RV9",
    "RVN",
    "RVNCG",
    "RW1",
    "RW4",
    "RW5",
    "RWK1G",
    "RWK1J",
    "RWK3A",
    "RWK79",
    "RWRD7",
    "RWRG3",
    "RWRG7",
    "RWRPJ",
    "RWRRG",
    "RWV",
    "RWX",
    "RX2",
    "RX301",
    "RX34F",
    "RX3YE",
    "RX4",
    "RXA29",
    "RXA52",
    "RXAWV",
    "RXE",
    "RXG10",
    "RXG82",
    "RXL",
    "RXM",
    "RXT",
    "RXV",
    "RXX1Y",
    "RXXY1",
    "RXY",
    "RY2",
    "RY6",
    "RYG",
    "RYK",
    "RYK14",
    "TAD",
    "TAF87",
    "TAF88",
    "TAF90",
    "TAH",
    "TAJ",
    "8J724",
    "8JX60",
    "8JY17",
    "AAF",
    "DD6",
    "DMK",
    "DV7",
    "DWY",
    "NQK",
    "RT119",
    "RT1AB",
    "RWK2T",
    "RWK4C",
    "RWK4D",
    "RWK53",
    "8JJ53",
    "AMC05",
    "DRL",
    "NDC17",
    "NDC18",
    "NWC05",
    "NWC07",
    "R0B",
    "RQYMI",
    "RRF",
    "RRPJ3",
    "RRPJ4",
    "RW501",
    "RW5ME",
    "RX40C",
    "RX4K3",
    "GDA01",
    "K7Y6R",
    "NWC10",
    "NWC11",
    "NWC12",
    "RJ8",
    "RKECE",
    "RT2",
    "T6G0K",
    "W5N3Z",
    "NMG",
    "NWC08",
    "P6W4I",
    "TAJ86",
    "8EJ83",
    "AMJ",
    "C1Y8W",
    "C2J4D",
    "DAX02",
    "NGR01",
    "NO401",
    "RQY58",
    "RDY",
    "S5F7C",
    "Z2E3K",
    "8HX13",
    "8KJ43",
    "E0W9O",
    "G6V2S",
    "G7X5M",
    "H7L3O",
    "M4P2I"
  )

  # Fetch ODS data
  provider_ods_data <- get_ods_data(provider_codes, add_names = TRUE)

  # Clean and select columns
  result <- provider_ods_data |>
    dplyr::mutate(
      org_name = clean_org_names(org_name),
      town = stringr::str_to_title(town),
      region_name = clean_org_names(
        stringr::str_replace_all(region_name, " COMMISSIONING REGION", "")
      ),
      icb_name = clean_org_names(
        stringr::str_replace_all(icb_name, " INTEGRATED CARE BOARD", "")
      )
    ) |>
    dplyr::select(
      org_code,
      org_name,
      status,
      start_date,
      end_date,
      postcode,
      town,
      icb_code,
      icb_name,
      region_code,
      region_name
    )

  arrow::write_parquet(result, cache_path)
  result
}
